# Generated by Django 6.0.2 on 2026-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('category', models.CharField(choices=[('design', '设计'), ('development', '开发'), ('writing', '写作'), ('translation', '翻译'), ('other', '其他')], max_length=50, verbose_name='任务分类')),
                ('reward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='悬赏金额')),
                ('deadline', models.DateField(verbose_name='截止日期')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('contact', models.CharField(max_length=200, verbose_name='联系方式')),
                ('publisher', models.CharField(default='匿名用户', max_length=100, verbose_name='发布者')),
                ('status', models.CharField(choices=[('open', '进行中'), ('completed', '已完成')], default='open', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
