# Generated by Django 6.0.2 on 2026-02-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assignee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='接受者'),
        ),
    ]
