# Generated by Django 6.0.2 on 2026-02-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_assignee'),
    ]

    operations = [
        # 跳过创建Category表，因为已经存在
        # 修改Task.category字段，添加新的分类选项
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('design', '设计'), ('development', '开发'), ('writing', '写作'), ('translation', '翻译'), ('reward', '悬赏'), ('game', '游戏'), ('trade', '交易'), ('charity', '公益'), ('other', '其他')], max_length=50, verbose_name='任务分类'),
        ),
    ]