# Generated by Django 6.0.2 on 2026-02-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontenduser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='frontenduser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='frontenduser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='frontenduser',
            name='user_permissions',
        ),
    ]
